<script type="text/x-magento-init">
    {
        "*": {
            "OpenTechiz_Blog/js/commentajax": {
                "AjaxCommentPostUrl": "<?php echo $block->getFormAction() ?>",
                "AjaxCommentLoadUrl": "<?php echo $block->getAjaxUrl() ?>",
                "AjaxPostId": "<?php echo $block->getPostID(); ?>"
            }
        }
    }
</script>
<?php $helper = $this->helper('OpenTechiz\Blog\Helper\UserInfo'); ?>
<form class="form" method="post" id="comment-form">
    <fieldset class="fieldset">
        <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Add new comment') ?></span></legend><br>
        <div class="note"></div>
        <?php if(!$helper->isLoggedIn()) { ?>
        <div class="field required">
            <label for="author" class="label">
                <span><?php /* @escapeNotVerified */ echo __('Name') ?></span>
            </label>

            <div class="control">
                <input type="text" id="author"
                       name="author"
                       class="input-text" width="50%">
            </div>
        </div>
        <?php } ?>
        <?php if(!$helper->isLoggedIn()) { ?>

        <div class="field required">
            <label for="email" class="label">
                <span><?php /* @escapeNotVerified */ echo __('Email') ?></span>
            </label>

            <div class="control">
                <input type="text" id="email"
                       name="email"
                       class="input-text" width="50%">
            </div>
        </div>
        <?php } ?>
        <div class="field required">
            <label for="content" class="label">
                <span><?php /* @escapeNotVerified */ echo __('Content') ?></span>
            </label>

            <div class="control">
                <textarea id="content"
                          name="content"
                          class="input-text"></textarea>
            </div>
        </div>
    </fieldset>
    <input type="hidden" name="post_id" value="<?php echo $block->getPostID() ?>"/>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" id="submit" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>">
                <span><?php /* @escapeNotVerified */ echo __('Submit') ?></span>
            </button>
        </div>
    </div>

</form>