<h1>Comments is not approve</h1>
<ul class="blog-cmt-no-active" id="not-active-new" style="color: blue;">
</ul>
<ul class="blog-cmt-no-active" id="data" style="color: red;">
</ul>
<script id="cmt-not-active" type="text/x-magento-template">
    <li class="blog-post-list-item"><%- cmt.author %>
        <div class="blog-post-item-content"><%- cmt.content %></div>
        <div class="blog-post-item-meta">
            <small>Created at: <%- cmt.creation_time %></small>
        </div>
    </li>
</script>